language: node_js
node_js:
  - "10.9"
before_install:
  - npm i -g npm@4.5.0
  - npm i -g @microsoft/rush
  - npm i -g grunt-cli
jobs:
  include:
    - stage: "Build and Test: DynamicProto JS"
      name: "Build and Test: DynamicProto JS"
      script:
      - npm run travisinit
      - npm install
      - npm run build
      - npm run test
